services:
  pytorch-gpu:
    command: apt-get update && apt-get install libgl1
    image: weedseg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8000:8000"
    volumes:
      - "./data:/etc/"
#      - "./models:/etc/UAVWeedSegmentation/models"
    ipc: host

