version: "3"
services:
  pytorch-gpu:
    image: weedseg

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8000:8000"
    volumes:
      - "./data:/etc/joe"
