services:
  pytorch-gpu:
#    command: 
#      - mkdir /etc/joe/UAVWeedSegmentation/models
#      - cp model_unet_resnet34_dil0_bilin1_retrained.pt /etc/joe/UAVWeedSegmentation/models
    image: weedseg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8000:8000"
    volumes:
      - "./data:/etc/joe"
      - "./models:/etc/joe/UAVWeedSegmentation/models"
    ipc: host

